### ISSUE TITLE
Sporadisch 502 Bad Gateway auf dem Server

### ISSUE THREAD

**Issue by localh0rzd** [DSIW/sdf#112]
Schritte zur Reproduktion:

- Nicht eingeloggt sein
- Öffentliches Buch anschauen (z.B. https://ws15sdf-b.f4.htw-berlin.de:8080/books/17/)
- Kaufen-Knopf drücken

Ergebnis: Etwa bei jedem zweiten Aufruf über den Knopf gibts einen HTTP 502 (direktes Aufrufen der URL ist kein Problem).

**Comment by DSIW** [comment]
So etwas hasse ich!

**Comment by DSIW** [comment]
Viele Exception-Email habe ich und Jens erhalten:

```
Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "/opt/venv/sdf-develop/lib/python3.4/site-packages/django/core/urlresolvers.py", line 393, in urlconf_module
    return self._urlconf_module
AttributeError: 'RegexURLResolver' object has no attribute '_urlconf_module'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venv/sdf-develop/lib/python3.4/site-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/opt/venv/sdf-develop/lib/python3.4/site-packages/django/core/urlresolvers.py", line 365, in resolve
    for pattern in self.url_patterns:
  File "/opt/venv/sdf-develop/lib/python3.4/site-packages/django/core/urlresolvers.py", line 401, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/opt/venv/sdf-develop/lib/python3.4/site-packages/django/core/urlresolvers.py", line 395, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/opt/venv/sdf-develop/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/var/www/sdf-develop/sdf/urls.py", line 27, in <module>
    url(r'^', include('app.urls', namespace='app')),
  File "/opt/venv/sdf-develop/lib/python3.4/site-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/opt/venv/sdf-develop/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/var/www/sdf-develop/app/urls.py", line 7, in <module>
    from . import views
  File "/var/www/sdf-develop/app/views.py", line 11, in <module>
    from .models import StaticPage
ImportError: cannot import name 'StaticPage'

Request repr(): 
<WSGIRequest
path:/accounts/login/,
GET:<QueryDict: {'next': ['/offers/12/start_payment/']}>,
POST:<QueryDict: {}>,
COOKIES:{'csrftoken': 'KyB6NPavMgNlKxRdCv2PhzYyzhmYdYdy'},
META:{'CONTENT_LENGTH': '',
 'CONTENT_TYPE': '',
 'DOCUMENT_ROOT': '/var/www/sdf-develop',
 'HTTPS': 'on',
 'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
 'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.5',
 'HTTP_CONNECTION': 'keep-alive',
 'HTTP_COOKIE': 'csrftoken=KyB6NPavMgNlKxRdCv2PhzYyzhmYdYdy',
 'HTTP_DNT': '1',
 'HTTP_HOST': 'ws15sdf-b.f4.htw-berlin.de:8080',
 'HTTP_REFERER': 'https://ws15sdf-b.f4.htw-berlin.de:8080/books/17/',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:43.0) '
                    'Gecko/20100101 Firefox/43.0',
 'PATH_INFO': '/accounts/login/',
 'QUERY_STRING': 'next=/offers/12/start_payment/',
 'REMOTE_ADDR': '87.168.161.187',
 'REMOTE_PORT': '62545',
 'REQUEST_METHOD': 'GET',
 'REQUEST_URI': '/accounts/login/?next=/offers/12/start_payment/',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'ws15sdf-b.f4.htw-berlin.de',
 'SERVER_PORT': '8080',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'uwsgi.node': b'ws15sdf-b',
 'uwsgi.version': b'2.0.7-debian',
 'wsgi.errors': <_io.TextIOWrapper name=2 mode='w' encoding='UTF-8'>,
 'wsgi.file_wrapper': <built-in function uwsgi_sendfile>,
 'wsgi.input': <uwsgi._Input object at 0x7f6a0609e750>,
 'wsgi.multiprocess': True,
 'wsgi.multithread': False,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'https',
 'wsgi.version': (1, 0)}>
```

**Comment by localh0rzd** [comment]
Hm, scheint etwas mit der Import-Reihenfolge zu tun zu haben.

https://github.com/omab/python-social-auth/issues/269#issuecomment-43424185

**Comment by DSIW** [comment]
Ich habe nun uwsgi auf dem Server komplett neugestartet. Dann konnte ich die Seite gar nicht mehr aufrufen, weil hier immer der Fehler von oben kam. Habe nun mit `git bisect` den Commit 93763a4519dff8ee4c5829d895bc9fb5b89d33bf ausfindig gemacht, der das Problem wohl verursacht. Wenn ich den Commit reverte, funktioniert die Anwendung auch wieder auf dem Server.

**Comment by ottmann** [comment]
So das lag an den Settings. Hatte die Einstellungen für das Caching nur in die Lokalen Settings mit aufgenommen, nicht aber in die vom Server. Hab ich nun ergänzt. Testen wir nachher und wenn es funktioniert, kann das Ticket geschlossen werden
