### ISSUE TITLE
Änderungsantrag: Error wenn E-Mailadresse bereits vorhanden ist.

### ISSUE THREAD

**Issue by ottmann** [DSIW/sdf#132]
Wenn bei der Änderung eine neue E-Mailadresse gesetzt wird, welche bereits vorhanden ist, gibt es eine Exception welche nicht behandelt wird und wir erhalten einen HTTP Error 500.
Fehler sollte behandelt werde.

```
Internal Server Error: /accounts/1/change_user_profile_accept/
Traceback (most recent call last):
  File "/opt/venv/sdf/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/opt/venv/sdf/lib/python3.4/site-packages/django/db/backends/sqlite3/base.py", line 318, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: UNIQUE constraint failed: auth_user.email
```

**Comment by ottmann** [comment]
Wäre vermutlich am besten, wenn der Fehler bereits beim User auftritt wenn er den Antrag stellt, damit dies erst gar nicht möglich ist.
